.\"Copyright 2010 (c) EPFL
.TH TESTPORT 1 2010 "EPFL" "lpttrigger library manual"
.SH NAME
testport - test the parallel port
.SH SYNOPSIS
.LP
.BI "testport [OPTIONS]"
.br
.SH DESCRIPTION
.LP
\fBtestport\fP aloows the user to test the parallel port by sending pulse to it.
.SH "OPTIONS"
.LP
\fBtestport\fP supports the following options:
.TP 7
\fB-base-level=LEVEL\fP
Change the rest level of the pins specified in hexadecimal (0x00)
.TP 7
\fB--delay=DELAY\fP
Set the delay in milliseconds before the pins are set to the rest level (200
ms)
.TP 7
\fB--port=PORTNUMBER\fP
Specify the parallel port to use. On windows, this value refers to the
memory address to use (0x378). On Linux, this refers to the number of
parport device to use (default is 0 which means that /dev/parport0 will be
used)
.TP 7
\fB-h, --help\fP
Display the help




